pyshepseg/tiling.py
@neilflood I think this is what you had in mind?
Note that when processing our test image (l8olre_p090r079_m201909201911_dbim6.img) with the default tileSize (4096) it now does it as one tile in this PR. But seems to work well with smaller tileSizes. 
Merge if you are happy...
=> ensure no tiles are smaller than tileSize as a simple way of avoiding slivers

pyshepseg/shepseg.py
Minor thing, but creating an array likely to be slower and more memory intensive than an iterator in numba... Output appears to be the same.
=> Use iterator instead of temporary array

pyshepseg/tiling.py, pyshepseg/utils.py
This is to be more compatible with RIOS (and ERDAS Imagine, should that matter). Also means counts won't overflow. I think the behaviour before was a bit undefined if the Histogram column already existed..
Maybe we should also have a different type for the `hist` array?
@petescarth bit of a long shot but I wonder if this may have helped with your mangled file?
=> Use Real type for histogram, plus check for existence first

pyshepseg/tiling.py, pyshepseg/utils.py
In some situations the user may have a RAT that has more segments than what is in the image. For example, if they have taken a subset. In this case some pages will not be written back to the file as they are never marked as 'complete'. 
I think we should deal with these situations. The attached PR ensures all incomplete pages are written at the end and a warning printed. I'd also be happy with raising an error in instead. I don't think we should let this go through undetected though. 
This also fixes with a problem not detecting we already have an Alpha column when creating a colour table. 
BTW I'm working on a new and improved "compress" algorithm to properly subset imagery and the RAT. Stay tuned.
cc: @petescarth
=> Catch any incomplete pages at end of stats processing and raise error

pyshepseg/tiling.py
This pull request changes the calcPerSegmentStatsTiled function so that the imgfile is opened in readonly mode. 
Opening the file in update mode causes problems if the file is accessed in S3 storage.
=> Open the imgfile as read only to support vsis3

pyshepseg/tiling.py
Fixes #19 
Ignores pixels that are equal to the nodata (if set). Really rough initial commit, will do more testing tomorrow. 
@neilflood any issues with this approach?
=> Handle nodata in source image during stats calculation

setup.py
Moving to `numpy.distutils` seems preferable to `setuptools`. This is what we did for RIOS.
=> use numpy.distutils as distutils now deprecated

parallel_examples/README.md, parallel_examples/awsbatch/Dockerfile, parallel_examples/awsbatch/README.md, parallel_examples/awsbatch/build_docker.sh, parallel_examples/awsbatch/create-stack.sh, parallel_examples/awsbatch/delete-stack.sh, parallel_examples/awsbatch/do_finalize.py, parallel_examples/awsbatch/do_prepare.py, parallel_examples/awsbatch/do_stitch.py, parallel_examples/awsbatch/do_tile.py, parallel_examples/awsbatch/modify-stack.sh, parallel_examples/awsbatch/push_to_ecr.sh, parallel_examples/awsbatch/submit-job.py, parallel_examples/awsbatch/template/template.yaml, pyshepseg/tiling.py
....so they can potentially be called in parallel.
As promised @neilflood here is a very rough PR. Let me know what you think before I tidy up.
The idea is that a users script would run `doTiledShepherdSegmentation_prepare()` before submitting a script to call `doTiledShepherdSegmentation_doOne()` for each tile into a batch queue or whatever. The actual mechanism for passing `tileInfo` and the other parameters to each script is left to the user. When all these jobs have finished another script should be run to call `doTiledShepherdSegmentation_finalize()`. 
This is quite a minor change compared to what could be done but my idea was to leave it to others to flesh out something for their particular use case and batch queuing system.
=> Make parts of doTiledShepherdSegmentation() separate

.readthedocs.yaml, doc/requirements.txt, doc/source/conf.py, doc/source/index.rst, pyshepseg/shepseg.py, pyshepseg/tiling.py, pyshepseg/tilingstats.py, pyshepseg/utils.py
Switch on numpydoc Sphinx extension, and have a go at re-formatting the shepseg module, to see how it might look. This is very much just to test and see. Initially only modified the shepseg module. It took a couple of hours, I think, but not too bad. 
Ping @gillins 
No rush. When you get a moment, have a look at the rendered RTD page, and at the original code, and see what you think. 
I think it is do-able, if we want to. It certainly does lots of nice formatting without the really dense docstrings that raw Sphinx requires, but it does still require some discipline. I have left some of the docstrings raw, because some are nice and short as they are, without needing much formatting. Or we could get really rigid and make everything conform to the same pattern. I dunno.....
I used the …
=> Testing Sphinx with numpydoc

pyshepseg/guardeddecorators.py, pyshepseg/shepseg.py, pyshepseg/tiling.py, pyshepseg/tilingstats.py
This kludge will allow classes decorated with `@jitclass` to also render in Sphinx with the numpydoc extension. These two don't play well together, so this fakes the jitclass decorator when running with sphinx. 
The last bit of ugliness I had to do was in shepseg.py, where I needed to make the `RowColArray_Type` declaration conditional on no sphinx. I tried several ways around this, but they either failed with sphinx, or failed when running for real, so this is all I have left. 
One thing I had hopes for was making the fake jitclass decorator return a derived class with an extra field for .class_type.instance_type. This works, in principle, but numpydoc won't render the resulting class, whereas if it returns the real original class, numpydoc renders it fine. I don't understand why. …
=> Numpydoc and jitclass

pyshepseg/subset.py, pyshepseg/tilingstats.py
I had exactly the same problem in tilingstats.writeCompletePages(), and have copied the same solution to subset.writeCompletedPagesForSubset(). 
The for loop should get the type right by itself, but it just gives int. I suspect that there is a deficiency in the way numa.typed.Dict makes it iterator, but that is for another day. (Note to self - look into this.....)
Anyway, this gets rid of the warning message.
=> Create array of page ID keys, to avoid NumbaTypeSafetyWarning

.readthedocs.yaml, pyshepseg/tiling.py
As spotted by @t-hackwood `pyshepseg` fails to do tiled segmentation with a recent scipy as it tries to index a scalar. The problem is that the behaviour changed in [scipy 1.9.0 ](https://docs.scipy.org/doc/scipy/release/1.9.0-notes.html) where a `keepdims` parameter was added to the stats functions. Now returns a scalar for 1d inputs by default. 
`keepdims=True` will revert to the previous behaviour (return a 1d array for 1d inputs), but since this wasn't an option on earlier scipy, this will break older installs. 
So my approach was to do a test on what is returned. Tested on scipy 1.8 and 1.12.
Any thoughts @neilflood (no hurry on this) ?
=> cope with new version of scipy and changed behaviour of stats.mode

pyshepseg/tiling.py
Fixes #51 (I think...)
@gillins If you get a chance, perhaps test on the case which brought this to your attention?
=> Guard against trying to subsample >100% of the data

parallel_examples/awsbatch/do_prepare.py, parallel_examples/awsbatch/do_stitch.py, parallel_examples/awsbatch/do_tile.py, parallel_examples/awsbatch/submit-pyshepseg-job.py
Also add `--tileprefix` so multiple jobs can run at once without clobbering each other's files.
And delete tiles ASAP to release space.
=> Add spatial stats step to AWS Batch

parallel_examples/awsbatch/submit-pyshepseg-job.py
if they have specified a `tileprefix`. In this case the filenames should all be unique so we don't have collisions if running multiple tiles segmentations at once on the same bucket.
=> make pickle filename unique

parallel_examples/awsbatch/do_stitch.py, pyshepseg/cmdline/runtests.py, pyshepseg/subset.py, pyshepseg/tiling.py, pyshepseg/utils.py
This PR does a few different things:
1. Returns the created dataset from doTiledShepherdSegmentation_finalize/doTiledShepherdSegmentation so it is all ready to use by the caller.
2. Writes the Histogram to the RAT by default (we have to calculate this anyway for the missing segments check)
3. Calculates overviews in AWS Batch
=> Streamline histogram and stats generation

parallel_examples/awsbatch/Dockerfile, parallel_examples/awsbatch/do_prepare.py, parallel_examples/awsbatch/do_stitch.py, parallel_examples/awsbatch/do_tile.py, parallel_examples/awsbatch/submit-pyshepseg-job.py, pyshepseg/tilingstats.py
`--noremove` will allow us to check the temporary files and would be useful for debugging.
=> Add --noremove option to tiling jobs. Pull out alignment code check into a separate function

pyshepseg/utils.py
Ends up with weird things like this under numpy 2.0:
```
STATISTICS_MEAN=np.float(7.8117557801917)
```
See https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed.
RIOS seems unaffected - perhaps it does not end up with numpy scalars when doing the statistics.
=> don't use repr for numpy scalars

doc/source/index.rst
Was a) broken so it rendered like and internal link, and b) pointed to miniconda which we try to discourage (nasty license surprises) and instead use miniforge.
=> fix broken link

.readthedocs.yaml
As per [this ReadTheDocs post ](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/), we now have to explicitly identify the Sphinx conf.py
=> Update .readthedocs.yaml for explicit conf.py

pyshepseg/tilingstats.py
A somewhat temporary hack to allow the RIOS-based stats routines to specify a separate outFile. This will not a permanent solution. The next proper release will have a better equivalent of this.
=> Add outFile= hack to calcPerSegmentSpatialStatsRIOS and calcPerSegmentStatsRIOS

pyshepseg/tilingstats.py
In this case it is likely to be a `/vsis3` filesystem which cannot be opened in update mode. If the user instead passes in an open dataset as a workaround, then it never gets closed before RIOS runs and seems to cause a HDF5 locking issue.
=> Don't open segmentation file in update mode if it doesn't need to be updated

pyshepseg/tilingstats.py
Minor annoyance, but gdalinfo/tuiview won't show the RAT on these temp files as they aren't set to thematic. It all works ok because KEA allows you to set a RAT on an athematic image but this guards against future KEA changes.
=> Set temporary file to thematic
